version: '3.8'

services:
  flaskapp:
    image: dexterx11/bookstore:latest
    environment:
      - FLASK_ENV=development
      - MYSQL_DATABASE=bookstore
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=bookstore
      - MYSQL_ROOT_PASSWORD=root_pass
      - MYSQL_ADDRESS=bookstore-db.ckquapo1urgv.us-east-1.rds.amazonaws.com
    ports:
      - "5000"
    networks:
      - bookstore_net
    deploy:
      replicas: 8
      restart_policy:
        condition: any
  nginx: 
      image: dexter11/bookstore-nginx:latest
      deploy:
        replicas: 3
        placement:
          max_replicas_per_node: 1
        restart_policy:
          condition: any
      ports:
        - target: 80
          published: 80
          protocol: tcp
          mode: ingress
      networks:
        - bookstore_net

networks:
  bookstore_net:
    driver: overlay
    attachable: true
